---
- name: "Read additional vars files {{ proxmox_include_vars_files }}"
  include_vars: "{{ item }}"
  ignore_errors: true
  loop: "{{ proxmox_include_vars_files }}"
  when: proxmox_include_vars_files is defined
  tags:
    - container
- name: Create container
  community.general.proxmox:
    node: "{{ physical_host }}"
    api_user: "{{ proxmox_api_user }}"
    #api_token_id: "{{ proxmox_api_token_id }}"
    #api_token_secret: "{{ proxmox_api_token_secret }}"
    api_password: "{{ proxmox_api_password }}"
    api_host: "{{ proxmox_api_host }}"
    hostname: "{{ inventory_hostname }}"
    ostemplate: "{{ proxmox_container_template_storage }}:vztmpl/{{ proxmox_container_template }}"
    cpus: "{{ proxmox_container_cpus }}"
    memory: "{{ proxmox_container_memory }}"
    disk: "{{ proxmox_container_disk }}"
    unprivileged: "{{ proxmox_container_unprivileged }}"
    netif: "{{ proxmox_container_network }}"
    state: present
    pubkey: "{{ proxmox_container_root_ssh_pubkeys }}"
    features: "{{ proxmox_container_features }}"
  delegate_to: localhost
  register: container_create
- name: Wait till Container is available under the new name
  pause:
    seconds: 3
  when: container_create.changed
  tags:
    - container
- name: Read container new ID
  community.general.proxmox:
    node: "{{ physical_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    api_host: "{{ proxmox_api_host }}"
    hostname: "{{ inventory_hostname }}"
    state: stopped
  delegate_to: localhost
  register: container_id
  when: container_create.changed
  tags:
    - container
- name: Read container existing ID and start container
  community.general.proxmox:
    node: "{{ physical_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    api_host: "{{ proxmox_api_host }}"
    hostname: "{{ inventory_hostname }}"
    state: started
  delegate_to: localhost
  register: container_id
  when: not container_create.changed
  tags:
    - container
- name: parse Container ID
  set_fact:
    container_id: "{{ container_id['msg'] | regex_search(' [0-9]+ ') | trim | int }}"
  tags:
    - container
- debug:
    var: container_id
- name: enable tun devices in container
  blockinfile:
    path: /etc/pve/lxc/{{ container_id }}.conf
    block: |
      lxc.cgroup2.devices.allow: c 10:200 rwm
      lxc.mount.entry: /dev/net dev/net none bind,create=dir
  delegate_to: "{{ physical_host }}"
  when:
    - proxmox_container_enable_tun == true
  tags:
    - vpn
    - tun
    - container

- name: Gather facts of new container 
  gather_facts:
